#########################
# Default plot settings #
#########################

# How many datapoints we move the window
step = 1;

# How many datapoints are included in the window
window = 100;

# Maximum Ks we will plot out to
max_ks = 2;

# Parse command line args
options(echo=TRUE) # if you want to see commands in output file
args <- commandArgs(trailingOnly = TRUE)
input_csv = args[1];

# Check that user gave a tree file
if (!exists("input_csv")) {
	cat("You must specify a csv file generated by wgd-plot.pl as input.\n");
	q("no", status = 1);
} else if (!file.exists(input_csv)) {
	cat(paste0("Could not locate '", input_csv, "' perhaps you made a typo?\n"));
	q("no", status = 1);
}

# Parse name we will use for output
out_name = sub("\\.csv$", ".pdf", input_csv, perl=T);

# Sliding window mean function
slideFunctMean <- function(data, window, step){
	total <- length(data)
	spots <- seq(from=1, to=(total-window), by=step)
	result <- vector(length = length(spots))
	for(i in 1:length(spots)){
		result[i] <- mean(data[spots[i]:(spots[i]+window)])
	}
	return(result)
}

# Sliding window median function
slideFunctMedian <- function(data, window, step){
	total <- length(data)
	spots <- seq(from=1, to=(total-window), by=step)
	result <- vector(length = length(spots))
	for(i in 1:length(spots)){
		result[i] <- median(data[spots[i]:(spots[i]+window)])
	}
	return(result)
}

# Read in csv
data = read.csv(input_csv);
data = data[order(data[,1]),];
data = subset(data, data[,1] < max_ks);

ks = slideFunctMedian(data[,1], window, step);
support = slideFunctMean(data[,2], window, step);

data = data.frame(ks, support);

pdf(out_name);
plot(data, type="l", main=paste0("Sliding window plot for '", input_csv, "'"), xlab=expression(paste('Initial Intraspecies Pairwise', ' K'[s])), ylab='Proportion of Quartets supporting WGD');
dev.off();
